name: Generate Contribution Pac-Man

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pac-Man
        uses: lowlighter/metrics@latest
        with:
          filename: pacman.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pacman: yes
          plugin_pacman_days: 30
          plugin_pacman_speed: 2
          plugin_pacman_saturation: 0.4
          output_action: commit
